version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .dev.env

  web:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .dev.env
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  postgres_data: